### PR TITLE
First file is added

### PR DESCRIPTION
**Pull request by MohammadKaif1**
First file is added

### CODE REVIEW

**Comment by aaryahjolia** [comment]
Write code and output inside 3 backticks (`). See other md files for example.

**Review by MohammadKaif1 — COMMENTED** [review]
Done @aaryahjolia

**Comment by aaryahjolia** [comment]
Do proper formatting of code,
Write ```cpp instead of only 3 backticks,
Differentiate the output and input with different boxes.

**Comment by aaryahjolia** [comment]
[https://www.javatpoint.com/cpp-oops-concepts](https://www.javatpoint.com/cpp-oops-concepts)

**Pull request closed without merging**
