### PR TITLE
Queue

### PR DESCRIPTION
**Pull request by deepshikha2708**
Added a file on queue.

### CODE REVIEW

**Comment by aaryahjolia** [comment]
This change is not eligible for a PR. Please add some more content.

**Comment by deepshikha2708** [comment]
ok I will!

**Comment by deepshikha2708** [comment]
I have added more content. Plz review it

**Comment by aaryahjolia** [comment]
As it's open source, We can't directly copy whole para from other source, We can copy some of the content only.
PS : It's good to see that you are mentioning credits.

**Comment by deepshikha2708** [comment]
Actually I used the source for mainly adding he suub topics part, ohherwise I tried to reduce the content in one line so that it will be easy to read and comprehend.

**Pull request merged**
