### PR TITLE
Added new problems of 800 rating

### PR DESCRIPTION
**Pull request by coderSuren**
Completed #55 issue

The screenshot attached below ensures the acceptance status of solutions provided
Capture

### CODE REVIEW

**Comment by aaryahjolia** [comment]
Hey, Try using cin instead of scanf and search for other syntaxes of C if you have any and convert it to cpp.

**Comment by coderSuren** [comment]
Sorry, I forgot to change it.
I have made all the changes and also updated the code in gfg ide links.

**Comment by aaryahjolia** [comment]
1000 rating problems you contributed are of 900 ratings.
Change the folder location.

**Comment by coderSuren** [comment]
> 1000 rating problems you contributed are of 900 ratings. Change the folder location.

I have checked it, they are 1000 rated problems. Attached screenshot fyr
Capture

**Comment by aaryahjolia** [comment]
But you are contributing 1543-A, 1689-B, 1705-B.

**Comment by coderSuren** [comment]
I think you got confused with my first two commits. Let me clear it, the first two commits are from PR #45. After completing PR #45 , I accidentally deleted 1000 rated problems from my local repo, so I had to add it again locally and push it to my fork. Hence there are two commits of problems 58A and 479A in this PR. And I have also added the five 800-rating problems mentioned in issue #55 in next commits. So kindly accept my PR.

**Comment by coderSuren** [comment]
@aaryahjolia Oh, I didn't know how it came there. I have removed them now. Please accept this PR.

**Comment by aaryahjolia** [comment]
As contributing website solutions is not feasible from HSOC POV, I'm reducing the level.

**Pull request merged**
