### PR TITLE
 1703-C.md

### PR DESCRIPTION
**Pull request by Pranjal360Agarwal**
Added two codes of 1703 - A,C.

### CODE REVIEW

**Comment by aaryahjolia** [comment]
1703 C is of 800 rating.
Also improve the variable names and add comments.

**Comment by Pranjal360Agarwal** [comment]
### **Please review the code.** I have worked upon all the parameters suggested.
Improved the variable names, optimized the code, and added effective comments.

**Comment by Pranjal360Agarwal** [comment]
Adding the solution of two problems - 1719/problem/A, 1720/problem/A of 800 ratings.

**Comment by aaryahjolia** [comment]
Closing the issue as discussed on discord.

**Pull request closed without merging**
