### PR TITLE
Cycle Detection In Linked List

### PR DESCRIPTION
**Pull request by ashmeet-chhabra**
resolves issue #11

### CODE REVIEW

**Comment by aaryahjolia** [comment]
The code is good. But instead of both files, Make a single 'Cycle Detection.md' File and place your code inside it just like [https://github.com/aaryahjolia/dsa_competitive-coding/blob/main/STL/Deque/swap()%20-%20Swap%202%20Deque.md](https://github.com/aaryahjolia/dsa_competitive-coding/blob/main/STL/Deque/swap()%20-%20Swap%202%20Deque.md)

**Comment by ashmeet-chhabra** [comment]
Thanks, I'll fix it now. I was just trying to do as said in contribution guidelines, it asked for a .cpp file.

**Comment by ashmeet-chhabra** [comment]
done!

**Comment by aaryahjolia** [comment]
LGTM, PR Approved!

**Pull request merged**
