### PR TITLE
[GSSoC'23] Added Binary Search Interview Questions

### PR DESCRIPTION
**Pull request by ENVIRYO2112VIT**

### CODE REVIEW

**Comment by ENVIRYO2112VIT** [comment]
Please refer to issue #225  and close it when done.

**Comment by ENVIRYO2112VIT** [comment]
Please do add the proper labels as I have done this under GSSoC'23 and assign it to me before closing.
Any feedback or modificaitions is appreciated !

**Comment by aaryahjolia** [comment]
Hi, Please read the [Important Announcement](https://github.com/aaryahjolia/dsa_competitive-coding/issues/305).
PR can only be made after the issue is assigned to you.

**Comment by ENVIRYO2112VIT** [comment]
> Hi, Please read the [Important Announcement](https://github.com/aaryahjolia/dsa_competitive-coding/issues/305).
> PR can only be made after the issue is assigned to you.

I have also raised an issue which is linked to this PR
Please check

**Comment by ENVIRYO2112VIT** [comment]
> > Hi, Please read the [Important Announcement](https://github.com/aaryahjolia/dsa_competitive-coding/issues/305).
> > PR can only be made after the issue is assigned to you.
> 
> I have also raised an issue which is linked to this PR
> Please check

Issue #225

**Pull request closed without merging**
