### PR TITLE
Add Array Problems

### PR DESCRIPTION
**Pull request by PriyanshuGarg26**

### CODE REVIEW

**Review by PriyanshuGarg26 — COMMENTED** [review]
ok

**Comment by aaryahjolia** [comment]
Hey, Move it to Leetcode folder.

**Comment by PriyanshuGarg26** [comment]
ok Sure

**Review by PriyanshuGarg26 — COMMENTED** [review]
Done

**Comment by aaryahjolia** [comment]
Remove python codes, Add proper comments.

**Comment by PriyanshuGarg26** [comment]
Pls Review Changes and merge it

**Pull request merged**
