### PR TITLE
Create Median_of_Two_Sorted_Arrays.md

### PR DESCRIPTION
**Pull request by Jainamrockk**
This is a hard level question from LeetCode

### CODE REVIEW

**Comment by SimranLahrani842** [comment]
How did u directly add code ? Did u raised the issue first?

**Comment by Jainamrockk** [comment]
What happened?

**Comment by Jainamrockk** [comment]
> How did u directly add code ? Did u raised the issue first?
What happened?

**Comment by aaryahjolia** [comment]
> How did u directly add code ? Did u raised the issue first?

Thank you for your help @SimranLahrani842 !

@Jainamrockk Please read the [Important Announcement](https://github.com/aaryahjolia/dsa_competitive-coding/issues/305).
PR can only be made after the issue is assigned to you.

**Pull request closed without merging**
