### PR TITLE
Binary Tree Traversal #27

### PR DESCRIPTION
**Pull request by surjyaneeh**
issue #27

### CODE REVIEW

**Comment by aaryahjolia** [comment]
Hey @surjyaneeh , Please include a description in each file along with their complexities.
Also write ```cpp instead of only ``` at starting of code so that github will show it coloured.
Also you can directly print the answers instead of storing, If possible write whole code.

**Comment by surjyaneeh** [comment]
> Hey @surjyaneeh , Please include a description in each file along with their complexities. Also write "``cpp" instead of only "```" at starting of code so that github will show it coloured. Also you can directly print the answers instead of storing, If possible write whole code.

Okay I will do the necessary changes and inform you once done.

**Comment by aaryahjolia** [comment]
Hey, Everything is perfect.
Just change the code to have only 1 function and directly print the answer in every case.
Ex : 
```cpp
void dfs(TreeNode* root, vector<int> &answer){
        if(root==NULL) return;
        dfs(root->left, answer);
        answer.push_back(root->val);
        dfs(root->right, answer);
    }
```
Only this function with cout instead of push back in every approach.

**Comment by surjyaneeh** [comment]
> Hey, Everything is perfect. Just change the code to have only 1 function and directly print the answer in every case. Ex :
> 
> ```c++
> void dfs(TreeNode* root, vector<int> &answer){
>         if(root==NULL) return;
>         dfs(root->left, answer);
>         answer.push_back(root->val);
>         dfs(root->right, answer);
>     }
> ```
> 
> Only this function with cout instead of push back in every approach.

@aaryahjolia I have made changes.

**Comment by aaryahjolia** [comment]
LGTM! PR Approved.
Thank you for contributing!

**Pull request merged**
